# Generated by Django 3.2.3 on 2021-05-23 19:14

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('web', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=500)),
                ('created', models.DateTimeField(default=datetime.datetime(2021, 5, 23, 19, 14, 37, 752920, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1, null=True)),
                ('comentario', models.CharField(blank=True, max_length=500, null=True)),
                ('created', models.DateTimeField(default=datetime.datetime(2021, 5, 23, 19, 14, 37, 753211, tzinfo=utc))),
                ('web', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='Documentation.docs')),
            ],
        ),
    ]
